import { Router } from "express";
import { fieldsRouter } from "./fields.routes.js";
import { schemasRouter } from "./schemas.routes.js";
import { tablesRouter } from "./tables.routes.js";
import { metadataRouter } from "./metadata.route.js";
import { relationsRouter } from "./relations.routes.js";
export const adminRouter = Router();
adminRouter.use("/tables", tablesRouter);
adminRouter.use("/fields", fieldsRouter);
adminRouter.use("/schemas", schemasRouter);
adminRouter.use("/relations", relationsRouter);
adminRouter.use("/metadata", metadataRouter);
